[project]
name = "cctv-scrapers"
version = "0.1.0"
description = "A pipeline to download cctv cameras and related tech from prominent vendors."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "httpx>=0.28.1",
    "ipykernel>=7.1.0",
    "loguru>=0.7.3",
    "open-clip-torch>=3.2.0",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "playwright>=1.57.0",
    "pre-commit>=4.3.0",
    "pyarrow>=22.0.0",
    "pydantic>=2.12.3",
    "pytest>=9.0.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.3",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "torch>=2.9.1",
    "ultralytics>=8.3.228",
]
