"""Catalog loading utilities for camera identification.

This module provides helpers to load the camera catalog from the parquet
dataset and to iterate over reference image files for embedding and
indexing.
"""

import json
from pathlib import Path
from typing import Any, Dict, Iterable, Tuple

import pandas as pd
from loguru import logger

from src.config import OUTPUT_DIR, PROJECT_ROOT
from src.models.camera import CameraRecord


def load_catalog(parquet_path: Path | str | None = None) -> Dict[str, CameraRecord]:
    r"""Load camera catalog from a parquet dataset.

    The parquet file is expected to follow the schema produced by the
    dataset builder in :mod:`src.pipeline.dataset_builder`, with columns
    such as ``camera_id``, ``model_name``, ``display_name``,
    ``image_urls``, ``image_files``, ``datasheet_url``, and
    ``specifications``.

    If ``parquet_path`` is not provided, the default path
    ``output/products.parquet`` under :data:`OUTPUT_DIR` is used.

    :param parquet_path: Optional path to the products parquet file
    :return: Mapping from ``camera_id`` to :class:`CameraRecord`
    :raises FileNotFoundError: If the parquet file does not exist
    """
    if parquet_path is None:
        parquet_path = OUTPUT_DIR / "products.parquet"
    else:
        parquet_path = Path(parquet_path)

    if not parquet_path.exists():
        raise FileNotFoundError(f"Parquet catalog not found: {parquet_path}")

    logger.info(f"Loading camera catalog from {parquet_path}")
    df = pd.read_parquet(parquet_path)

    catalog: Dict[str, CameraRecord] = {}

    for _, row in df.iterrows():
        camera_id = str(row.get("camera_id") or "").strip()
        if not camera_id:
            logger.warning("Skipping row without camera_id")
            continue

        try:
            record = _row_to_camera_record(row)
        except Exception as exc:  # pragma: no cover - defensive
            logger.error(f"Failed to build CameraRecord for {camera_id}: {exc}")
            continue

        catalog[camera_id] = record

    logger.info(f"Loaded {len(catalog)} camera records from catalog")
    return catalog


def iter_reference_image_files(
    catalog: Dict[str, CameraRecord],
    project_root: Path | str | None = None,
    max_images_per_camera: int = 1,
) -> Iterable[Tuple[str, Path]]:
    r"""Iterate over reference image files for catalog cameras.

    For each :class:`CameraRecord` in the catalog, yields up to
    ``max_images_per_camera`` image paths derived from the ``image_files``
    field. Relative paths are resolved against ``project_root`` (or the
    current project root if not provided).

    :param catalog: Mapping from camera ID to :class:`CameraRecord`
    :param project_root: Base directory for resolving relative paths
    :param max_images_per_camera: Maximum number of images per camera to yield
    :return: Iterable of ``(camera_id, image_path)`` tuples
    """
    if project_root is None:
        base = PROJECT_ROOT
    else:
        base = Path(project_root)

    for camera_id, record in catalog.items():
        if not record.image_files:
            continue

        count = 0
        for rel_path in record.image_files:
            path = Path(rel_path)
            if not path.is_absolute():
                path = base / path

            if not path.exists():
                logger.debug(f"Skipping missing image file for {camera_id}: {path}")
                continue

            yield camera_id, path
            count += 1

            if count >= max_images_per_camera:
                break


def _parse_json_field(raw: Any, default: Any) -> Any:
    """Parse a JSON-encoded field from the parquet dataset.

    :param raw: Raw value from the dataframe row
    :param default: Default value if parsing fails or value is empty
    :return: Parsed Python object or ``default``
    """
    if raw is None:
        return default

    if isinstance(raw, float) and pd.isna(raw):
        return default

    if isinstance(raw, str):
        value = raw.strip()
        if not value:
            return default
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return default

    return default


def _row_to_camera_record(row: Any) -> CameraRecord:
    """Convert a dataframe row into a :class:`CameraRecord`.

    This helper assumes the standard schema generated by the dataset
    builder and handles JSON decoding for list/dict fields.

    :param row: Pandas Series representing a single row
    :return: Constructed :class:`CameraRecord`
    """
    image_urls = _parse_json_field(row.get("image_urls"), default=[])
    image_files = _parse_json_field(row.get("image_files"), default=[])
    specs_html = _parse_json_field(row.get("specifications"), default={})

    camera_id = str(row.get("camera_id"))
    model_name = str(row.get("model_name") or camera_id)
    display_name = str(row.get("display_name") or model_name)

    record = CameraRecord(
        camera_id=camera_id,
        model_name=model_name,
        display_name=display_name,
        description=row.get("description"),
        specifications={},
        image_url=image_urls[0] if image_urls else None,
        images=image_urls,
        image_files=image_files,
        datasheet_url=row.get("datasheet_url"),
        datasheet_file=row.get("datasheet_file"),
        specifications_html=specs_html,
        source=str(row.get("source") or "Unknown"),
        category=str(row.get("category") or "Unknown"),
        product_category=str(row.get("product_category") or "Unknown"),
        product_series=str(row.get("product_series") or "Unknown"),
    )

    return record
